CREATE TABLE students (
	student_id INT(11) AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR (50) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    birth_date DATE,
    gender VARCHAR (1),
    address VARCHAR(50),
    email VARCHAR(50),
    phone_number VARCHAR(11),
    program_id VARCHAR (11)
);

CREATE TABLE enrollments(
	enrollment_id INT (11) AUTO_INCREMENT PRIMARY KEY,
    student_id INT(11),
    course_id INT(10),
    class_id INT(11),
    enrollment_date DATE,
    status VARCHAR(15),
    FOREIGN KEY (student_id) REFERENCES students(student_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id),
    FOREIGN KEY (class_id) REFERENCES classes(class_id)
);

CREATE TABLE prerequisites(
	course_id INT(10),
    prerequisite_id INT(10),
    PRIMARY KEY (course_id,prerequisite_id),
    FOREIGN KEY (course_id) REFERENCES courses (course_id),
    FOREIGN KEY (prerequisite_id) REFERENCES courses (course_id)
);

CREATE TABLE coursecapacity(
    course_id INT(10) PRIMARY KEY,
    current_enrollment INT(45) DEFAULT 0,
    max_capacity INT(45) NOT NULL,
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

-- Values for liberal arts --
INSERT INTO Courses (course_id, course_name, units, instructor_id, prerequisite_id, college_id) VALUES

    	('CLA CORE1', 'Logic and Critical Thinking', 3, 136, NULL, 4),
    	('CLA CORE2', 'Citizenship and Governance', 3, 137, NULL, 4),
    	('CLA CORE3', 'Wika, Kultra at Media', 3, 138, NULL, 4),
    	('CLA CORE4', 'Gender Studies & Multiculturalism', 3, 139, NULL, 4),
    	('CLA CORE5', 'Creative Writing', 3, 140, NULL, 4),
    	('PEOPHIL', 'Peoples of the Philippines', 3, 137, NULL, 4),
	('SOTHEO1', 'Sociological Theories', 3, 136, NULL, 4),
	('ORGABEV', 'Organizational Behavior', 3, 138, NULL, 4),
	('HUMAREM', 'Human Resource Management', 3, 140, NULL, 4),
	('ORGANIV', 'Organizational Development and Leadership', 3, 139, NULL, 4),
	('SOTHEO2', 'Anthropological Theories', 3, 137, NULL, 4),
	('CHANGES', 'Change Management', 3, 136, NULL, 4),
	('GROPROC', 'Group Dynamics', 3, 138, NULL, 4),
	('SOCSSES', 'Socio-cultural Assessment Methodologies', 3, 140, NULL, 4),
	('SOCSTAT', 'Social Statistics', 3, 139, NULL, 4),
	('SOCRES1', 'Social Research 1', 3, 137, NULL, 4),
	('QUANTIPRO', 'Quantitative Data Processing and Analysis', 6, 136, NULL, 4),
	('PROGDEV', 'Program Development - SL', 3, 138, NULL, 4),
	('SOCRES2', 'Social Research 2', 3, 140, NULL, 4),
	('QUALIPRO', 'Qualitative Data Processing and Analysis', 6, 139, NULL, 4),
	('RESWRIT', 'Research Writing in the Social Sciences', 3, 137, NULL, 4),
	('THEOSD1', 'Thesis 1', 3, 136, NULL, 4),
	('PRACOSD', 'Practicum [300 hours]', 6, 138, NULL, 4),
	('SOCHEAL', 'Society and Health', 3, 140, NULL, 4),
	('SOCIORG', 'Sociology of Organizations and Industry', 3, 139, NULL, 4),
	('THEOSD2', 'Thesis 2', 3, 137, NULL, 4),
	('SOCPHIL', 'Sociological Analysis of the Philippine Society', 3, 136, NULL, 4),
	('SOCSTRA', 'Social Stratification, Mobility, and Change', 3, 138, NULL, 4),
	('SOCPROB', 'Social Problems', 3, 140, NULL, 4),
	('COMMDEV', 'Community Development', 3, 139, NULL, 4),
	('KNOWMAN', 'Knowledge Management', 3, 137, NULL, 4);
    	('SOCDEVT', 'Social Development', 3, 136, 'POLIGOV', 4),
    	('DEVECON', 'Development Economics', 3, 138, 'POLIGOV', 4),
    	('PHILDEV', 'Philippine Development', 3, 140, 'POLIGOV', 4),
    	('DEVTMAN', 'Development Management', 3, 139, NULL, 4),
    	('DEVEFIN', 'Development Finance', 3, 137, 'DEVECON', 4),
    	('PLANDEV', 'Development Planning', 3, 136, 'SOCDEVT, DEVECON', 4),
    	('DEVCOMM', 'Development Communication', 3, 138, 'DEVTMAN', 4),
    	('INTDEVT', 'International Development', 3, 140, 'SOCDEVT, DEVECON', 4),
    	('MANPROJ', 'Management of Development Projects', 3, 139, 'DEVTMAN', 4),
    	('COMDEVT', 'Community Development', 3, 137, 'SOCDEVT', 4),
    	('ACREDEV', 'Action Research in Development', 3, 136, 'SOCDEVT, DEVECON', 4),
    	('PRCDSM1', 'Practicum', 3, 138, 'Completed all major courses', 4),
    	('MINOR', 'Minor in Political Science and Development Studies', 0, 140, NULL, 4),
    	('LEGISLA', 'Seminar in Legislation', 3, 139, NULL, 4),
    	('PIPOISU', 'Philippine Political Issues', 3, 137, NULL, 4),
    	('POLLANG', 'Political Language', 3, 136, NULL, 4),
    	('PIPOLEC', 'Philippine Political Economy', 3, 138, NULL, 4),
    	('ENVIPOL', 'Environmental Politics', 3, 140, NULL, 4),
    	('FIGURES', 'Political Personalities', 3, 139, NULL, 4),
    	('PARTIES', 'Political Parties and Party Systems', 3, 137, NULL, 4),
    	('POLMARK', 'Political Marketing', 3, 136, NULL, 4),
    	('CONTEST', 'Political Contestation', 3, 138, NULL, 4),
    	('POLIGEN', 'Politics of Sex', 3, 140, NULL, 4),
    	('WOMEPOL', 'Women and Politics', 3, 139, NULL, 4),
    	('DEVISSU', 'Development Issues', 3, 137, NULL, 4),
    	('DEVTPER', 'Development Perspectives', 3, 136, NULL, 4),
    	('DEVINST', 'Development Institutions', 3, 138, NULL, 4),
    	('PEACEDE', 'Peace and Development', 3, 140, NULL, 4),
    	('SUSDEVT', 'Sustainable Development', 3, 139, NULL, 4),
    	('URBADEV', 'Urban Development', 3, 137, NULL, 4),
   	('DEVADVO', 'Development Advocacy', 3, 136, NULL, 4),
    	('HISTINT', 'Introduction to the Study and Writing of History', 3, 139, NULL, 4),
    	('HISTPOH', 'Philosophy of History', 3, 137, NULL, 4),
    	('HISTMET', 'Historical Methodology', 3, 136, NULL, 4),
    	('HISTEAS', 'Survey of Asian Civilizations', 3, 138, NULL, 4),
    	('HISTWES', 'Survey of Western Civilization', 3, 140, NULL, 4),
    	('HISTOG1', 'Historiography of the Philippines 1', 3, 139, NULL, 4),
    	('HISTOG2', 'Historiography of the Philippines 2', 3, 137, NULL, 4),
    	('HISTOG3', 'Historiography of the Philippines 3', 3, 136, NULL, 4),
    	('HISTPRE', 'Pre-16th Century Philippines', 3, 138, NULL, 4),
    	('HISTSOC', 'Philippine Social History', 3, 140, NULL, 4),
    	('HISTETN', 'Ethnic Histories', 3, 139, NULL, 4),
    	('HISTNAT', 'Nationalism and History', 3, 137, NULL, 4);
		
INSERT INTO Courses (course_id, course_name, units, instructor_id, prerequisite_id, college_id) VALUES
	('HISTANT', 'Ancient World History', 3, 136, NULL, 4),
    	('HISTMED', 'Medieval World History', 3, 138, NULL, 4),
    	('HISTMOD', 'Modern World History', 3, 140, NULL, 4),
    	('HISTCONT', 'Contemporary World History', 3, 139, NULL, 4),
    	('HISTSEA', 'History of Southeast Asia', 3, 137, NULL, 4),
    	('HISTCHN', 'History of China', 3, 136, NULL, 4),
    	('HISTJPN', 'History of Japan', 3, 138, NULL, 4),
    	('HISTUS', 'History of the United States', 3, 140, NULL, 4),
    	('HISTEUR', 'European History', 3, 139, NULL, 4),
    	('HISTLAT', 'Latin American History', 3, 137, NULL, 4),
    	('HISTAFR', 'History of Africa', 3, 136, NULL, 4),
    	('HISTSCI', 'History of Science and Technology', 3, 138, NULL, 4),
    	('HISTREL', 'History of Religions', 3, 140, NULL, 4),
    	('HISTWOM', 'Women in History', 3, 139, NULL, 4),
    	('HISTEN1', 'Environmental History 1', 3, 137, NULL, 4),
    	('HISTEN2', 'Environmental History 2', 3, 136, NULL, 4),
    	('HISTFIL', 'Film and History', 3, 138, NULL, 4),
    	('HISTART', 'Art and History', 3, 140, NULL, 4),
    	('HISTLIT', 'Literature and History', 3, 139, NULL, 4),
    	('HISTMAP', 'Maps and Geography in History', 3, 137, NULL, 4),
    	('HISTPOL', 'Politics in History', 3, 136, NULL, 4),
    	('HISTECO', 'Economics in History', 3, 138, NULL, 4),
    	('HISTSOC2', 'Sociology in History', 3, 140, NULL, 4),
    	('HISTMED2', 'Medical History', 3, 139, NULL, 4),
    	('HISTWAR', 'History of Warfare', 3, 137, NULL, 4),
    	('HISTTH1', 'Historical Thought 1', 3, 136, NULL, 4),
    	('HISTTH2', 'Historical Thought 2', 3, 138, NULL, 4),
    	('HISTTH3', 'Historical Thought 3', 3, 140, NULL, 4),
    	('HISTDIG', 'Digital History', 3, 139, NULL, 4),
    	('HISTPUB', 'Public History', 3, 137, NULL, 4),
    	('HISTARC', 'Archaeology and History', 3, 136, NULL, 4),
    	('HISTGEN', 'Genocide Studies', 3, 138, NULL, 4),
   	('HISTMEM', 'Memory Studies', 3, 140, NULL, 4),
    	('HISTMIN', 'Minority Histories', 3, 139, NULL, 4),
    	('HISTFAM', 'Family Histories', 3, 137, NULL, 4),
    	('HISTINQ', 'Inquiries in History', 3, 136, NULL, 4),
    	('HISTEMO', 'Emotions in History', 3, 138, NULL, 4),
    	('HISTIND', 'Independent Study in History', 3, 140, NULL, 4),
   	('HISTCAP', 'Capstone in History', 3, 139, NULL, 4)
	('IPOLECO', 'International Political Economy', 3, 136, 'INSTUDI, POLIGOV, ENGLTRI', 4),
	('EURHIST', 'European History', 3, 137, 'INSTUDI, POLIGOV, ENGLTRI', 4),
	('EUPOGOV', 'Seminar on Government & Politics of EU States', 3, 138, 'NONE', 4),
	('EUROECO', 'European Economics', 3, 139, 'EURHIST', 4),
	('EUROFOR', 'European Foreign Relations', 3, 140, 'PHILFOR', 4),
	('INTTLAW', 'Introduction to International Law', 3, 141, 'INTEORG', 4),
	('EUROLEC', 'European Elective', 3, 142, 'NONE', 4),
	('EUROCON', 'European Contemporary Issues', 3, 143, 'NONE', 4),
	('EURORE1', 'Thesis Proposal Writing for European Studies', 3, 144, 'RESMETH', 4),
	('SEMPRAC', 'Practicum Course', 3, 145, 'NONE', 4),
	('AREASEM', 'Seminar in Area Studies', 3, 146, 'NONE', 4),
	('EURORE2', 'Thesis Writing Proper', 3, 147, 'EURORE1', 4),
	('ELEMFRE', 'Elementary French', 3, 148, 'NONE', 4),
	('INTEFRE', 'Intermediate French 1', 3, 149, 'ELEMFRE', 4),
	('FRENCH3', 'Intermediate French 2', 3, 150, 'INTEFRE', 4),
	('FRENCH4', 'Advanced French', 3, 151, 'FRENCH3', 4),
	('FRENCH5', 'Advanced French Conversation', 3, 152, 'FRENCH4', 4),
	('SPANONE', 'Elementary Spanish', 3, 153, 'NONE', 4),
	('SPANTWO', 'Intermediate Spanish', 3, 154, 'SPANONE', 4),
	('SPANTRI', 'Advanced Spanish 1', 3, 155, 'SPANTWO', 4),
	('SPANFOR', 'Advanced Spanish 2', 3, 156, 'SPANTRI', 4),
	('SPANFIV', 'Readings in Hispano-Philippine Literature', 3, 157, 'SPANFOR', 4)
	('JAPALA1', 'Elementary Nihongo 1', 3, 137, NULL, 4),
    	('JAPALA2', 'Elementary Nihongo 2', 3, 138, 'JAPALA1', 4),
    	('JAPALA3', 'Intermediate Nihongo 1', 3, 139, 'JAPALA2', 4),
    	('JAPALA4', 'Intermediate Nihongo 2', 3, 140, 'JAPALA3', 4),
   	('JAGOPOL', 'Japanese Government and Politics', 3, 136, NULL, 4),
    	('JAPALIT', 'Japanese Literature', 3, 137, NULL, 4),
   	('JAPASOC', 'Japanese Society and Culture', 3, 138, NULL, 4),
    	('JAPALA5', 'Advanced Nihongo 1', 3, 139, 'JAPALA4', 4),
    	('JAPCINE', 'Japanese Cinema', 3, 140, NULL, 4),
    	('JAPECON', 'Japanese Economic History', 3, 136, NULL, 4),
    	('JAPAHIS', 'Japanese History', 3, 137, NULL, 4),
    	('JAPALA6', 'Advanced Nihongo 2', 3, 138, 'JAPALA5', 4),
    	('JAPHIRE', 'Japan-Philippine Foreign Relations', 3, 139, NULL, 4),
    	('JRESMET', 'Research on Japanese Studies', 3, 140, NULL, 4),
    	('JAPALA7', 'Advanced Nihongo 3', 3, 136, 'JAPALA6', 4),
    	('JAPALA8', 'Advanced Nihongo 4', 3, 137, 'JAPALA6', 4),
    	('JAPRES1', 'Japanese Research 1', 3, 138, 'RESMETH', 4),
    	('JAPRES2', 'Japanese Research 2', 3, 139, 'JAPRES1', 4);

INSERT INTO Courses (course_id, course_name, units, instructor_id, prerequisite_id, college_id) VALUES
    ('LITSTUD', 'Introduction to Literature and Literary Studies', 3, 141, NULL, 4),
    ('LITTHEO', 'Introduction to Literary Theory', 3, 142, NULL, 4),
    ('LITCULT', 'Introduction to Cultural Theory', 3, 143, NULL, 4),
    ('LITPOCO', 'Introduction to the Postcolonial Tradition', 3, 144, NULL, 4),
    ('LITCREW', 'Introduction to Creative Writing', 3, 145, NULL, 4),
    ('LITITRA', 'Introduction to Translation', 3, 146, NULL, 4),
    ('LITPROF', 'Introduction to Literature & the Professions (Service Learning)', 3, 147, NULL, 4),
    ('LITRESE', 'Literary Research (Capstone)', 3, 148, NULL, 4)
    ('LITGENT', 'Genre: Techniques', 3, 149, NULL, 4),
    ('LITWOR1', 'Workshop 1', 3, 150, NULL, 4),
    ('LITWOR2', 'Workshop 2', 3, 151, NULL, 4),
    ('LITGCPO', 'Genre Concept & Poetics', 3, 152, NULL, 4),
    ('LITEDIT', 'Editing', 3, 153, NULL, 4),
    ('LITMEDI', 'Writing for Media for Literature Majors', 3, 154, NULL, 4),
    ('LITWORM', 'World Masterpieces', 3, 155, NULL, 4),
    ('LITPHIM', 'Philippine Masterpieces', 3, 156, NULL, 4),
    ('LITMAJ1', 'Literature Elective 1', 3, 157, NULL, 4),
    ('LITMAJ2', 'Literature Elective 2', 3, 158, NULL, 4),
    ('LITMAJ3', 'Literature Elective 3', 3, 159, NULL, 4),
    ('LITMAJ4', 'Literature Elective 4', 3, 160, NULL, 4),
    ('SPANONE', 'Spanish 1', 3, 161, NULL, 4),
    ('SPANTWO', 'Spanish 2', 3, 162, 'SPANONE', 4),
    ('THS1LIT', 'Thesis 1 (3.0 units)', 3, 163, 'LITRESE', 4),
    ('THS2LIT', 'Thesis 2 (6.0 units)', 6, 164, 'THS1LIT', 4),
    ('PRCLIT1', 'Practicum (6.0 units)', 6, 165, NULL, 4)
    ('LITPREG', 'Phil Lit: Region & Nation', 3, 149, NULL, 4),
    ('LITPTHE', 'Phil Lit Theory & Criticism', 3, 150, NULL, 4),
    ('LITAFRO', 'Lit of Africa', 3, 151, NULL, 4),
    ('LITASI1', 'Lit of Asia 1-East Asia', 3, 152, NULL, 4),
    ('LITASI2', 'Lit of Asia 2-Southeast Asia', 3, 153, NULL, 4),
    ('LITEURO', 'Lit of Europe', 3, 154, NULL, 4),
    ('LITAMER', 'Lit of the Americas', 3, 155, NULL, 4),
    ('LITTRAN', 'Literary Translation', 3, 156, NULL, 4)
    ('FILSTUD', 'Introduction to Philippine Studies', 3, 157, NULL, 4),
    ('FILCULM', 'Introduction to Philippine Popular Culture in Mass Media', 3, 158, NULL, 4),
    ('FILDISK', 'Introduction to Media Discourse in Filipino', 3, 159, NULL, 4),
    ('FILMCRI', 'Media Criticism in Filipino', 3, 160, NULL, 4),
    ('FILDIAS', 'The Diaspora of Filipino Culture', 3, 161, NULL, 4),
    ('FILDUBS', 'Introduction to Audiovisual Translation', 3, 162, NULL, 4),
    ('FILANG1', 'Chinese Language', 3, 163, NULL, 4),
    ('FILANG2', 'Spanish Language', 3, 164, NULL, 4),
    ('FILJORN', 'Filipino Journal', 3, 165, NULL, 4),
    ('FILARAP', 'Analysis of Radio and Print Media Materials in Filipino', 3, 157, NULL, 4),
    ('FILATMA', 'Analysis of Television Materials in Filipino', 3, 158, NULL, 4),
    ('FILTRAN', 'Translation Techniques', 3, 159, NULL, 4),
    ('FEAWRIT', 'Feature Writing', 3, 160, NULL, 4),
    ('FILREMA', 'Research sa Pangmasang Midya sa Filipino', 3, 161, NULL, 4),
    ('PRCPHM1', 'Practicum', 6, 162, NULL, 4),
    ('THSPHM1', 'Tesis sa Filipino', 6, 163, NULL, 4),
    ('CONPHIL', 'The Philippines in the 20th Century', 3, 164, NULL, 4),
    ('CULTHIS', 'Cultural History of the Philippines', 3, 165, NULL, 4),
    ('PHILNAT', 'Philippine Nationalism and Social Movements', 3, 157, NULL, 4),
    ('FIFPHILO', 'Filipino Philosophy', 3, 158, NULL, 4),
    ('LITHIST', 'Kasaysayan ng Panitikang Pilipino', 3, 159, NULL, 4),
    ('SOCIETY', 'Mass Media and Society', 3, 160, NULL, 4),
    ('FILCRIT', 'Translation Criticism', 3, 161, NULL, 4),
    ('FILFILM', 'Filipino Film', 3, 162, NULL, 4),
    ('FILGENS', 'Identity, Gender, and Subjectivity', 3, 163, NULL, 4);

INSERT INTO Courses (course_id, course_name, units, instructor_id, prerequisite_id, college_id) VALUES
	('FUNPOLS', 'Fundamentals of Political Science', 3, 136, NULL, 4),
	('POLTHE1', 'Political Theory I', 3, 137, NULL, 4),
	('POLTHE2', 'Political Theory II', 3, 138, 'POLTHE1', 4),
	('POLQUAN', 'Quantitative Research Methods', 3, 139, NULL, 4),
	('POLQUAL', 'Qualitative Research Methods', 3, 140, NULL, 4),
	('POLLRES', 'Political Research', 3, 141, 'POLQUAN', 4),
	('COMPOLG', 'Introduction to Comparative Politics & Government', 3, 142, NULL, 4),
	('POLGOVT', 'Philippine Politics and Government', 3, 143, 'COMPOLG', 4),
	('POLLSEA', 'Comparative Politics & Government of Southeast Asia', 3, 144, 'COMPOLG', 4),
	('POLIDEM', 'Comparative Politics & Government of Democracies', 3, 145, 'COMPOLG', 4),
	('POLIECO', 'Introduction to Political Economy', 3, 146, NULL, 4),
	('PUBLIAD', 'Introduction to Public Administration', 3, 147, NULL, 4),
	('POLDESI', 'Policy Analysis and Design', 3, 148, 'PUBLIAD', 4),
	('GOVESEM', 'Seminar in Governance', 3, 149, 'POLDESI', 4),
	('INTTREL', 'Introduction to International Relations', 3, 150, NULL, 4),
	('INTLORG', 'International and Regional Organizations', 3, 151, 'INTTREL', 4),
	('PRCPOMA', 'Political Science Practicum 1', 3, 152, NULL, 4),
	('PRCPOMB', 'Political Science Practicum 2', 3, 153, 'PRCPOMA', 4),
	('THSPOM1', 'Senior Research in Political Science 1', 3, 154, 'POLQUAN', 4),
	('THSPOM2', 'Senior Research in Political Science 2', 3, 155, 'THSPOM1', 4),
	('POMELE1', 'Political Science Elective 1', 3, 156, NULL, 4),
	('POMELE2', 'Political Science Elective 2', 3, 157, NULL, 4),
	('CINEPOL', 'Cinema and Politics', 3, 158, NULL, 4),
	('CRITPOL', 'Critical Political Theory and Analysis', 3, 159, NULL, 4),
	('CULPOLI', 'Culture and Politics', 3, 160, NULL, 4),
	('EGOVERN', 'E-Governance', 3, 161, NULL, 4),
	('ENVIGOV', 'Environmental Governance', 3, 162, NULL, 4),
	('LAWPOLS', 'Law, Politics and Society', 3, 163, NULL, 4),
	('LOCALGO', 'Local Politics and Governance', 3, 164, NULL, 4),
	('PIPOLEC', 'Philippine Political Economy', 3, 165, NULL, 4),
	('PIPOISU', 'Philippine Political Issues', 3, 136, NULL, 4),
	('POLECOL', 'Political Ecology', 3, 137, NULL, 4),
	('POLMARK', 'Political Marketing', 3, 138, NULL, 4),
	('PARTIES', 'Political Parties and Party Systems', 3, 139, NULL, 4),
	('POLICUM', 'Politics of Culture and Media', 3, 140, NULL, 4),
	('POLEDUC', 'Politics of Education', 3, 141, NULL, 4)
	('INPRINT', 'Introduction to Theory and History: Print', 3, 136, NULL, 4),
	('INTROFI', 'Introduction to Theory and History: Film', 3, 137, NULL, 4),
	('INBROAD', 'Introduction to Theory and History: Broadcasting', 3, 138, NULL, 4),
	('INTRORE', 'Introduction to Research for Production', 3, 139, NULL, 4),
	('FOTOCOM', 'Introduction to Photography for Communication Majors', 3, 140, NULL, 4),
	('VIDPROD', 'Workshop on Video Production', 3, 141, 'FOTOCOM', 4),
	('RADIPRO', 'Radio Production', 3, 142, 'INBROAD', 4),
	('PRINPRO', 'Print Production', 3, 143, 'INPRINT, ARTCOMP', 4),
	('TELEPRO', 'Television Production', 3, 144, 'RADIPRO, VIDPROD', 4),
	('FILMMAN', 'Film Video Production Management', 3, 145, 'INTROFI, VIDPROD', 4),
	('BRODMAN', 'Broadcast Journalism Management', 3, 146, 'Senior standing', 4),
	('PRINMAN', 'Print Production Management', 3, 147, 'Senior standing', 4),
	('FOTPRAC', 'Professional Practices in Photography', 3, 148, 'Senior standing', 4),
	('SOCIETY', 'Mass Media and Society', 3, 149, 'INPRINT, INTROFI, INBROAD, FOTOCOM, INTRORE', 4),
	('PROJCO1', 'Projects in Communication 1', 1.5, 150, 'Senior standing', 4),
	('PROJCO2', 'Projects in Communication 2', 1.5, 151, 'PROJCO1', 4),
	('FOTESTH', 'History and Aesthetic Theories of Photography', 3, 152, 'FOTOCOM', 4),
	('FOTSHOP', 'Adobe Photoshop', 3, 153, 'PRINPRO, FOTOCOM', 4),
	('FOTESAY', 'Photo Essay', 3, 154, 'FOTOCOM, INTRORE', 4),
	('STUDIOS', 'Studios Photography', 3, 155, 'FOTOCOM', 4),
	('FOTJORN', 'Photojournalism', 3, 156, 'FOTOCOM', 4),
	('FOTOLIT', 'Light and Photography', 3, 157, 'FOTOCOM', 4),
	('MASFOTO', 'Masters in Photography', 3, 158, 'FOTOCOM', 4),
	('FOCOLOR', 'Color Photography', 3, 159, 'FOTOCOM', 4),
	('PHOTOAD', 'Photography in Advertising', 3, 160, 'FOTOCOM', 4),
	('ADPHOTO', 'Art Direction in Photography', 3, 161, 'FOTOCOM', 4),
	('PROGRAM', 'Broadcast Programming', 3, 162, 'INBROAD', 4),
	('DEPRICO', 'Design in Print Communication', 3, 163, 'PRINPRO, INPRINT', 4),
	('DESTELE', 'Design in Television', 3, 164, 'INBROAD, TELEPRO', 4),
	('NEWSRIT', 'News and Feature Writing', 3, 165, 'INPRINT', 4),
	('FILPRES', 'The Philippine Press', 3, 136, 'INPRINT', 4),
	('BROJORN', 'Broadcast Journalism', 3, 137, 'INBROAD, INPRINT', 4),
	('ENGNEWS', 'Electronic News Gathering', 3, 138, 'INBROAD, BROJORN, VIDPROD', 4),
	('DOCFILM', 'The Documentary in Film and Video', 3, 139, 'INTROFI', 4),
	('DESFILM', 'Design in Film', 3, 140, 'INTROFI', 4),
	('ANIMATE', 'Film Animate', 3, 141, 'INTROFI, VIDPROD', 4),
	('THEORIE', 'Film Theory and Criticism', 3, 142, 'INTROFI', 4),
	('PERFORM', 'Performance in Media', 3, 143, 'INTROFI, VIDPROD', 4),
	('POSPROD', 'Post Production Techniques', 3, 144, 'INTROFI, VIDPROD', 4),
	('CINEMAT', 'Basic Cinematography', 3, 145, 'INTROFI, VIDPROD', 4),
	('MASFILM', 'Masters in Film', 3, 146, NULL, 4),
	('ESTHETE', 'Aesthetics of Film and Video', 3, 147, NULL, 4),
	('FEATURE', 'Feature Film', 3, 148, 'INTROFI, WRIFILM, VIDPROD', 4),
	('WRIFILM', 'Writing for Film', 3, 149, 'INTROFI, VIDPROD', 4),
	('POPCULT', 'Popular Culture', 3, 150, NULL, 4),
	('PROPLAN', 'Seminar in Production Planning', 3, 151, 'Senior standing', 4);

INSERT INTO Courses (course_id, course_name, units, instructor_id, prerequisite_id, college_id) VALUES
	('ORGTHEO', 'Organizational Theory and Dynamics', 3, NULL, NULL, 4),
	('COMTHEO', 'Communication Theory', 3, NULL, NULL, 4),
	('ETHICOM', 'Ethics in Communication', 3, NULL, NULL, 4),
	('RESERCH', 'Research for Organizations', 3, NULL, NULL, 4),
	('DESKTOP', 'Desktop Publishing', 3, NULL, NULL, 4),
	('GRAPHIC', 'Graphic Design and Production', 3, NULL, 'DESKTOP', 4),
	('ORGAVID', 'Organizational Video', 3, NULL, 'DESKTOP', 4),
	('PUBLIRE', 'Public Relations', 3, NULL, 'ETHICOM', 4),
	('MANACOM', 'Management in Communication', 3, NULL, NULL, 4),
	('COMTECH', 'Communication Technology', 3, NULL, NULL, 4),
	('ORGADEV', 'Organizational Change and Development', 3, NULL, 'MANACOM', 4),
	('WORKONE', 'Projects in Organizational Communication 1', 1.5, NULL, NULL, 4),
	('WORKTWO', 'Projects in Organizational Communication 2', 1.5, NULL, 'WORKONE', 4),
	('CORCULT', 'Corporate Culture', 3, NULL, 'ORGTHEO', 4),
	('POLIORG', 'Power and Politics in Organizations', 3, NULL, 'ORGTHEO', 4),
	('PERSUAD', 'Persuasion Theory', 3, NULL, 'COMTHEO', 4),
	('POLICOM', 'Political Communication', 3, NULL, 'COMTHEO', 4),
	('PHILORG', 'Philippine Culture in Organizations', 3, NULL, 'ORGTHEO', 4),
	('IMAGEAD', 'Image Advertising', 3, NULL, NULL, 4),
	('AUDIPRO', 'Audio Production', 3, NULL, NULL, 4),
	('EDBROAD', 'Educational Broadcasting', 3, NULL, NULL, 4),
	('ISSUMAN', 'Issues Management', 3, NULL, 'PUBLIRE', 4),
	('NEGORES', 'Negotiations, Mediation, and Dispute Resolution in Organization', 3, NULL, 'ORGTHEO', 4),
	('CAMPAIN', 'Campaign Management', 3, NULL, 'ORGADEV', 4),
	('SPECVID', 'Video for Specific Organizational Needs', 3, NULL, 'ORGAVID', 4)
	('THINKIN', 'Logic and Critical Thinking', 3, 136, NULL, 4),
	('PHILPRO', 'Introduction to Philosophical Problems', 3, 137, NULL, 4),
	('PLMWOMN', 'Women in Philosophy', 3, 138, NULL, 4),
	('PLMSYLO', 'Symbolic Logic', 3, 139, NULL, 4),
	('PLMANCI', 'Ancient Philosophy', 3, 140, NULL, 4),
	('PLMEDVL', 'Medieval Philosophy', 3, 141, NULL, 4),
	('PLMRELS', 'Philosophy of Religion', 3, 142, NULL, 4),
	('PLMINDI', 'Indian Philosophy', 3, 143, NULL, 4),
	('PLMMDRN', 'Modern Philosophy', 3, 144, NULL, 4),
	('PLMSOCI', 'Social and Political Philosophy', 3, 145, NULL, 4),
	('PLMCHIN', 'Chinese Philosophy', 3, 146, NULL, 4),
	('PLMFILI', 'Filipino Philosophy', 3, 147, NULL, 4),
	('PLMCONT', 'Contemporary Epistemology', 3, 148, NULL, 4),
	('PLMEXIS', 'Existentialism and Phenomenology', 3, 149, NULL, 4),
	('PLMLANG', 'Philosophy of Language', 3, 150, NULL, 4),
	('PLMPOST', 'Postmodernism', 3, 151, NULL, 4),
	('PLMESTH', 'Aesthetics', 3, 152, NULL, 4),
	('PLMMORP', 'Moral Philosophy', 3, 153, NULL, 4),
	('PLMMETA', 'Contemporary Metaphysics', 3, 154, NULL, 4),
	('PLMSCIE', 'Philosophy of Science', 3, 155, NULL, 4),
	('PLMMIND', 'Philosophy of Mind', 3, 156, NULL, 4),
	('PLMELE1', 'Philosophy Elective 1', 3, 157, NULL, 4),
	('PLMELE2', 'Philosophy Elective 2', 3, 158, NULL, 4),
	('PLMELE3', 'Philosophy Elective 3', 3, 159, NULL, 4)
	('EPYLEC', 'Experimental Psychology (Lecture)', 3, 136, NULL, 4),
	('EPYLAB', 'Experimental Psychology (Laboratory)', 2, 137, 'EPYLEC', 4),
	('TOP', 'Theories of Personality', 3, 138, NULL, 4),
	('COGPSY', 'Cognitive Psychology', 3, 139, NULL, 4),
	('ABPSY', 'Abnormal Psychology', 3, 140, NULL, 4),
	('PMEAS1', 'Psychological Measurement 1 (Lecture)', 2, 141, NULL, 4),
	('PMEAS1L', 'Psychological Measurement 1 (Laboratory)', 1, 142, 'PMEAS1', 4),
	('SP', 'Sikolohiyang Pilipino', 3, 143, NULL, 4),
	('BIOPSY', 'Biological Psychology', 3, 144, NULL, 4),
	('PMEAS2', 'Psychological Measurement 2 (Lecture)', 2, 145, 'PMEAS1', 4),
	('PMEAS2L', 'Psychological Measurement 2 (Laboratory)', 1, 146, 'PMEAS2', 4),
	('SOCPSY', 'Social Psychology', 3, 147, NULL, 4),
	('FIELDM', 'Field Methods in Psychology', 5, 148, NULL, 4),
	('METHPSY', 'Methods of Psychological Research', 3, 149, NULL, 4),
	('CLINPSY', 'Clinical Psychology', 3, 150, NULL, 4),
	('IOPSY1', 'Industrial / Organizational Psychology 1', 3, 151, NULL, 4),
	('DEVPSY', 'Developmental Psychology', 3, 152, NULL, 4),
	('IOPSY2', 'Industrial / Organizational Psychology 2', 3, 153, 'IOPSY1', 4),
	('SEMSPS1', 'Seminar in Psychology 1 - Sport Psychology', 3, 154, NULL, 4),
	('INTERNP', 'Internship in Psychology', 3, 155, NULL, 4),
	('THES1', 'Thesis in Psychology 1', 1.5, 156, NULL, 4),
	('SEMSPS2', 'Seminar in Psychology 2 - Positive Psychology', 3, 157, NULL, 4),
	('THES2', 'Thesis in Psychology 2', 1.5, 158, 'THES1', 4),
	('SEMSPS2H', 'Seminar in Psychology 2 - Health Psychology', 3, 159, NULL, 4);

INSERT INTO Prerequisites (course_id, prerequisite_id) 
VALUES 
('SOCDEVT', 'POLIGOV'),
('DEVECON', 'POLIGOV'),
('PHILDEV', 'POLIGOV'),
('DEVEFIN', 'DEVECON'),
('PLANDEV', 'SOCDEVT'),
('PLANDEV', 'DEVECON'),
('DEVCOMM', 'DEVTMAN'),
('INTDEVT', 'SOCDEVT'),
('INTDEVT', 'DEVECON'),
('MANPROJ', 'DEVTMAN'),
('COMDEVT', 'SOCDEVT'),
('ACREDEV', 'SOCDEVT'),
('ACREDEV', 'DEVECON'),
('PRCDSM1', 'Completed all major courses'), --idk how to do this
('IPOLECO', 'INSTUDI'),
('IPOLECO', 'POLIGOV'),
('IPOLECO', 'ENGLTRI'),
('EURHIST', 'INSTUDI'),
('EURHIST', 'POLIGOV'),
('EURHIST', 'ENGLTRI'),
('EUROECO', 'EURHIST'),
('EUROFOR', 'PHILFOR'),
('INTTLAW', 'INTEORG'),
('EURORE1', 'RESMETH'),
('EURORE2', 'EURORE1'),
('INTEFRE', 'ELEMFRE'),
('FRENCH3', 'INTEFRE'),
('FRENCH4', 'FRENCH3'),
('FRENCH5', 'FRENCH4'),
('SPANTWO', 'SPANONE'),
('SPANTRI', 'SPANTWO'),
('SPANFOR', 'SPANTRI'),
('SPANFIV', 'SPANFOR'),
('JAPALA2', 'JAPALA1'),
('JAPALA3', 'JAPALA2'),
('JAPALA4', 'JAPALA3'),
('JAPALA5', 'JAPALA4'),
('JAPALA6', 'JAPALA5'),
('JAPALA7', 'JAPALA6'),
('JAPALA8', 'JAPALA6'),
('JAPRES1', 'RESMETH'),
('JAPRES2', 'JAPRES1');

INSERT INTO Prerequisites (course_id, prerequisite_id) 
VALUES
('POLTHE2', 'POLTHE1'),
('POLLRES', 'POLQUAN'),
('POLGOVT', 'COMPOLG'),
('POLLSEA', 'COMPOLG'),
('POLIDEM', 'COMPOLG'),
('POLDESI', 'PUBLIAD'),
('GOVESEM', 'POLDESI'),
('INTLORG', 'INTTREL'),
('PRCPOMB', 'PRCPOMA'),
('THSPOM1', 'POLQUAN'),
('THSPOM2', 'THSPOM1'),
('SOCIETY', 'INPRINT'),
('SOCIETY', 'INTROFI'),
('SOCIETY', 'INBROAD'),
('SOCIETY', 'FOTOCOM'),
('SOCIETY', 'INTRORE'),
('PROJCO2', 'PROJCO1'),
('VIDPROD', 'FOTOCOM'),
('RADIPRO', 'INBROAD'),
('PRINPRO', 'INPRINT'),
('TELEPRO', 'RADIPRO'),
('FILMMAN', 'INTROFI'),
('BRODMAN', 'Senior standing'),
('PRINMAN', 'Senior standing'),
('FOTPRAC', 'Senior standing'),
('PROJCO2', 'PROJCO1'),
('FOTESTH', 'FOTOCOM'),
('FOTSHOP', 'PRINPRO'),
('FOTESAY', 'FOTOCOM'),
('STUDIOS', 'FOTOCOM'),
('FOTJORN', 'FOTOCOM'),
('FOTOLIT', 'FOTOCOM'),
('MASFOTO', 'FOTOCOM'),
('FOCOLOR', 'FOTOCOM'),
('PHOTOAD', 'FOTOCOM'),
('ADPHOTO', 'FOTOCOM'),
('PROGRAM', 'INBROAD'),
('DEPRICO', 'PRINPRO'),
('DESTELE', 'INBROAD'),
('NEWSRIT', 'INPRINT'),
('FILPRES', 'INPRINT'),
('BROJORN', 'INBROAD'),
('ENGNEWS', 'INBROAD'),
('DOCFILM', 'INTROFI'),
('DESFILM', 'INTROFI'),
('ANIMATE', 'INTROFI'),
('THEORIE', 'INTROFI'),
('PERFORM', 'INTROFI'),
('POSPROD', 'INTROFI'),
('CINEMAT', 'INTROFI'),
('FEATURE', 'INTROFI'),
('WRIFILM', 'INTROFI')
('GRAPHIC', 'DESKTOP'),
('ORGAVID', 'DESKTOP'),
('PUBLIRE', 'ETHICOM'),
('ORGADEV', 'MANACOM'),
('WORKTWO', 'WORKONE'),
('CORCULT', 'ORGTHEO'),
('POLIORG', 'ORGTHEO'),
('PERSUAD', 'COMTHEO'),
('POLICOM', 'COMTHEO'),
('PHILORG', 'ORGTHEO'),
('ISSUMAN', 'PUBLIRE'),
('NEGORES', 'ORGTHEO'),
('CAMPAIN', 'ORGADEV'),
('SPECVID', 'ORGAVID'),
('EPYLAB', 'EPYLEC'),
('PMEAS1L', 'PMEAS1'),
('PMEAS2L', 'PMEAS2'),
('IOPSY2', 'IOPSY1'),
('THES2', 'THES1');





    
